### PR TITLE
Fix for cache problem when used as widget

### PR DESCRIPTION
**Pull request by iqit-commerce**
Fix for issue report https://github.com/PrestaShop/PrestaShop/issues/14423

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/105)

### CODE REVIEW

**Comment by sarahdib** [comment]
Hello @iqit-commerce 

Thank you for this contribution :)

The price slider is not visible anymore

image

**Comment by iqit-commerce** [comment]
@sarahdib 

It is not related, rang sldier is not visible becouse you put it as widget withoit removing it from left column, so now it is duplicated, If you unhook from left column so you will have only one instance then it will be ok

**Comment by sarahdib** [comment]
Ok that was the only problem the PR is ok for me :) 

Thank you

**Comment by PierreRambaud** [comment]
Thanks @iqit-commerce

**Pull request merged**
