### PR TITLE
Add sorting by reference

### PR DESCRIPTION
**Pull request by LameuleFR**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add sorting by reference in the prestashop categorie page.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Check that on the category with filters there is a new sorting option available

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/925)

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]
LGTM

**Comment by florine2623** [comment]
@LameuleFR ,

Do you have an issue/discussion related ? If so, please add the link to your PR description.
If not, please describe How to test your PR description.

**Review by kpodemski — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @LameuleFR ,

I have checked your PR and the sorting by reference is well added in the PrestaShop category page and works as expected.

LGTM :green_circle: 

It is QA approved ! 
Thanks.

**Comment by kpodemski** [comment]
thank you @LameuleFR

**Comment by jf-viguier** [comment]
Some merchants don't use references, so this sorting is not relevant for them.

**Comment by LameuleFR** [comment]
In most case merchant will use references but we can probably add a configuration field in the module to activate/deactivate this behaviour.

**Comment by kpodemski** [comment]
@LameuleFR It would be great to have a simple configuration for every sort option 👍🏻

**Pull request merged**
