### PR TITLE
Release 3.12.1

### PR DESCRIPTION
**Pull request by lartist**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Merge dev into master
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  |

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/806)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @lartist

**Comment by Hlavtox** [comment]
@lartist Wrong milestone name

**Comment by HanaRebaiQA** [comment]
Hello @lartist 

I have checked you PR.

On PS8.0.2 : OK
On PS17.8.8. : OK

**Comment by jolelievre** [comment]
Thanks @HanaRebaiQA and @lartist

**Pull request closed without merging**
