### PR TITLE
Release 3.9.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.9.0 version
| Type?         | -
| BC breaks?    | -
| Deprecations? | -
| Fixed ticket? | -
| How to test?  | -

- - -
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/756)

### CODE REVIEW

**Comment by Hlavtox** [comment]
QA - Ignore failing coverage/coveralls test, not relevant, it's like this on almost every PR.

**Comment by MhiriFaten** [comment]
Hello ! 

This PR should be approved before putting the **`waiting for QA`** label !
I will remove the label.

Thank you.

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Tested on 1.7.8.8 and 8.0.0 with PHP 7.4.

Tested the module in general and these PRs in particular:

https://github.com/PrestaShop/ps_facetedsearch/pull/679 ✅ 
https://github.com/PrestaShop/ps_facetedsearch/pull/691 ✅ 
https://github.com/PrestaShop/ps_facetedsearch/pull/692 ✅ 
https://github.com/PrestaShop/ps_facetedsearch/pull/726 ✅ 
https://github.com/PrestaShop/ps_facetedsearch/pull/728 ✅ 
https://github.com/PrestaShop/ps_facetedsearch/pull/754 ✅ 

It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
Thanks, @Hlavtox and all other contributors for this version! :)

**Pull request merged**
