### PR TITLE
Release 3.13.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.13.1
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Release Test

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/894)

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by boherm — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Review by AureRita — COMMENTED** [review]
Hi @Progi1984 

Thank you for your PR, I tested it on : 

8.0.4 :x: that what I got : 

[Untitled_ Aug 3, 2023 5_23 PM.webm](https://github.com/PrestaShop/ps_facetedsearch/assets/100699445/36421380-a4e8-4daa-9ee6-633ca62988ab)

1.7.8.9 :x:  I have the same things than 8.0.4
1.7.8.10 :x: I have the same things than 8.0.4 

8.1.0 :x: like the 8.0.4, it don't wan't to be in 3.13.1, it'll go in 3.13.0 but I have a red screen when I update the module : 

image

for the other I have : 
8.1.1 :heavy_check_mark: 
8.0.5 :heavy_check_mark: 


as you can see : 

[Untitled_ Aug 3, 2023 5_30 PM.webm](https://github.com/PrestaShop/ps_facetedsearch/assets/100699445/a5afdad5-c81c-456c-a617-106d0da588d6)

**Comment by Hlavtox** [comment]
@AureRita You are not using the correct branch, you don't even have the updated texts in module settings.

**Comment by AureRita** [comment]
Hi @Hlavtox, 

as you can see on the last video, with the correct version, I've the update text and other else modification. I use always the same version for all of it

**Comment by Hlavtox** [comment]
@AureRita No, you don't, on 8.0.4, you were testing with 3.13.0. But I guess that's understandable when you don't do anything the whole day and then you try to test everything in 1 hour after I notify your supervisor.
 
Snímek obrazovky 2023-08-03 215603

**Comment by matks** [comment]
@Hlavtox Your message is clearly against the [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).

**Comment by leemyongpakvn** [comment]
> @AureRita You are not using the correct branch, you don't even have the updated texts in module settings.

I think @Hlavtox is right, but it is not the AureRita's intend ;) As we can see in the screencast, we only can upgrade to `v3.13.0` that **absolutely not** what we try to check. The behind-the-scene problem can be [ps_distributionapiclient](https://github.com/PrestaShop/ps_distributionapiclient) or [native-modules](https://github.com/PrestaShop/native-modules/blob/main/ps_facetedsearch.yml). But again, it is out of this PR scope.
So I suggest a new tactic (you can call it a trick, a work around, a rude way or whatever, but it works :) for QA team to test this Release PR
1) In Terminal
```
cd modules
rm -rf ps_facetedsearch
git clone https://github.com/PrestaShop/ps_facetedsearch.git
cd ps_facetedsearch
composer install
nvm use 16
npm install
npm run build
``` 
2) In Back-Office > IMPROVE >Modules > Module Manager
choose Configure > Reset

**Comment by Hlavtox** [comment]
@leemyongpakvn That's not how the PRs are tested. This release is not yet on distribution api, so if it offers upgrade from 3.13.0 to 3.13.0, it's not the issue with this module, but some core issue. 

We can see from the first video, that after opening module configuration, @AureRita does have the old module installed. Even if the upgrade script failed, you would still see the new texts in module configuration. This release has nothing to do with it.

@PrestaShop/qa-automation Can you assign someone to test this PR? [All changes in this version are mine](https://github.com/PrestaShop/ps_facetedsearch/pulls?q=is%3Apr+is%3Amerged+milestone%3A3.13.1+) and my clients expect the update to be delivered as soon as possible.

**Comment by kpodemski** [comment]
Hello

For installation with distribution API, I recommended deleting `/var/cache` after placing the upgraded version in your `modules` directory. This will clear the distribution API cache, and all upgrades should be visible.

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/committers it seems there's a failed check, could you please check 🙏 
Thanks in advance!

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@hibatallahAouadni I restarted the failed tests

**Comment by AureRita** [comment]
Hi @Progi1984 

After some test with @hibatallahAouadni, your PR works as expected on 8.0.4 / 8.0.5 / 8.1.1  :heavy_check_mark: 

but the version isn't displayed well because of the API module, as we can see here : 

[Untitled_ Aug 9, 2023 5_33 PM.webm](https://github.com/PrestaShop/ps_facetedsearch/assets/100699445/8409451c-f946-4579-91c1-4dcae5f39416)

because this issue is not because of this PR, it's a QA :heavy_check_mark: 

Special thank to @boherm that help us when we need some help for this PR 

Thanks

**Pull request merged**
