### PR TITLE
Make the search more cacheable & scalable by removing temp table creation

### PR DESCRIPTION
**Pull request by jocel1**
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/25)

### CODE REVIEW

**Comment by jocel1** [comment]
Quick win to improve performances: facetedsearch can run on slave db server, and most queries can now be cached in memcached / mysql query_cache.

**Comment by eternoendless** [comment]
:lgtm:

For the record: it looks like subqueries are faster than temporary tables

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/ps_facetedsearch/25#-:-Kwo30iB0-cYB_lEnePA:b7rkf8s)*

**Comment by prasanthSelvar** [comment]
Hello @jocel1 
I can't use anymore navigation filters with these changes.
Is the same for you?

Thanks

**Comment by jocel1** [comment]
@prasanthSelvar this should not be the case, do you have any SQL error reported in dev mode?

**Comment by prasanthSelvar** [comment]
@jocel1 sorry that's was a mistake on my side.
I haven't any SQL error reported, it's OK for me.

**Comment by eternoendless** [comment]
@jocel1 did you take the changes from https://github.com/PrestaShop/ps_facetedsearch/pull/24 into account?

**Comment by jocel1** [comment]
@eternoendless mmm not yet, I'll check this right now

**Comment by jocel1** [comment]
For me #24 is invalid. However I found and fixed a bug in the current PR where the selected category list were not correctly initlalized!

**Comment by jocel1** [comment]
@eternoendless I've just pushed a fix for the bug reported in #25

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/ps_facetedsearch/25#-:-KxCQ5Dqffbk2JJq9lGc:bnfp4nl)*

**Comment by eternoendless** [comment]
Thank you @jocel1

**Pull request merged**
