### PR TITLE
Fix PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix PHP 8.4 compatibility
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @jolelievre ready to go :-)

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@jolelievre Can I merge this one?

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Yep, no functional change However, the release PR will need to be tested

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Pull request merged**
