### PR TITLE
Release version 3.12.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release version 3.12.0
| Type?         | 
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  |

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/798)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thank you @djoelleuch! 😎

**Comment by ChronoBrake** [comment]
Hey, when filers will working on manufacturers pages? Still in file be info:

```
getManufacturersBlock
        // TODO - Needed to make manufacturer filter work (=disappear) on manufacturer page, not sure how it works.
        // (Manufacturer's page is the only page having id_manufacturer as the initial filter, that's why.)
```

Best Regards

**Comment by Hlavtox** [comment]
@ChronoBrake It works perfectly since 3.11, this TODO is just for me to better understand how it works, sometimes. :-)

**Comment by Hlavtox** [comment]
@ChronoBrake You need to enable the pages in the settings of filtering template

**Comment by AlexR1712** [comment]
> @ChronoBrake You need to enable the pages in the settings of filtering template

Hi! This is not working for me on manufacturer pages, works fine on category pages but on manufacturer page even if I confirm that is enabled for manufacturer it does not show :/

Any suggestions?

I'm using: 
- PS 1.7.8.7
- ps_facetedsearch v3.15.1

**Pull request merged**
