### PR TITLE
Fix [BOOM-2025] ps_facetedsearch - Filter products by the stock of matched variants, not just any of them

### PR DESCRIPTION
**Pull request by PeNov**
https://github.com/PrestaShop/PrestaShop/issues/10018

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/43)

### CODE REVIEW

**Comment by jolelievre** [comment]
can you run php-cs-fixer please?

**Comment by jolelievre** [comment]
also the version should be updated so that the module is opened to upgrade

**Comment by Quetzacoalt91** [comment]
Thank you @PeNov

**Comment by khouloudbelguith** [comment]
Hi @PeNov,

We have this issue https://github.com/PrestaShop/PrestaShop/issues/12143 after upgrade from v2.2.0 to v2.2.1.
Thanks!

**Comment by pdkey** [comment]
@khouloudbelguith thanks for your info - i will wait for your solution.

**Pull request merged**
