### PR TITLE
Bump version number to 3.11.1

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | bug fix / improvement / new feature / refacto / critical
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes PrestaShop/Prestashop#{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/790)

### CODE REVIEW

**Comment by Hlavtox** [comment]
ping @kpodemski for merge

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
@Hlavtox do we need QA? I don't think so but I prefer to be sure, I made mistake on tuesday 😬

**Comment by Hlavtox** [comment]
Not on version bump, but Krystian said to wait for https://github.com/PrestaShop/ps_facetedsearch/pull/789 to be merged. 👍

**Comment by nicosomb** [comment]
Thank you @Hlavtox

**Pull request merged**
