### PR TITLE
Release 3.15.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Release 3.15.0
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

### CODE REVIEW

**Review by M0rgan01 — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@florine2623 @jolelievre Guys can you please investigate when this issue goes away, so we can fix it if it's related to the attribute pr? https://github.com/PrestaShop/PrestaShop/issues/35331

**Comment by jolelievre** [comment]
> @florine2623 @jolelievre Guys can you please investigate when this issue goes away, so we can fix it if it's related to the attribute pr? [PrestaShop/PrestaShop#35331](https://github.com/PrestaShop/PrestaShop/issues/35331)

Yes, I'll have a look at it today

**Comment by Hlavtox** [comment]
@jolelievre It could either be the cache of the blocks OR the attribute index of the module. 👍

**Comment by MatShir** [comment]
On 8.1.3 it works after clearing the cache

**Review by boherm — APPROVED** [review]

**Review by MatShir — CHANGES_REQUESTED** [review]
Waiting for https://github.com/PrestaShop/ps_facetedsearch/pull/983

**Review by matks — APPROVED** [review]

**Review by MatShir — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
@florine2623

**Review by florine2623 — APPROVED** [review]
Hello @jolelievre ,

Tested on :
- 8.0.x (old product page)
- 8.1.x (new product page, old attributes page)
- develop (new product page, new attributes page)

https://github.com/PrestaShop/PrestaShop/issues/35331 is fixed

Tested deletion/disabling of attributes with and without rebuilding index or clearing the cache.

LGTM ✅ 

Thanks!

**Pull request merged**
