### PR TITLE
Fix wrong filter price, need match shop current

### PR DESCRIPTION
**Pull request by alex4102**

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and thanks for your contribution.
Can you update unit tests?

**Comment by alex4102** [comment]
I updated tests but I dont know, why I have this error : "Mockery\Exception\BadMethodCallException: Method Mockery_2_Db::executeS() does not exist on this mock object"

**Comment by PierreRambaud** [comment]
I fixed your tests and squash your commit ;)

**Comment by alex4102** [comment]
> I fixed your tests and squash your commit ;)

Thanks

**Comment by PierreRambaud** [comment]
Thanks @alex4102

**Pull request merged**
