### PR TITLE
Correctly serialize and unserialize parameters in URLs.

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Correctly serialize and unserialize parameters in URLs.
| Type?         | bug fix
| BC breaks?    | yes
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#16320
| How to test?  | See ticket.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/275)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@PierreRambaud PHPStan isn't happy!

**Comment by PierreRambaud** [comment]
> @PierreRambaud PHPStan isn't happy!

I notice phpstan is badly implemented in GA. My fault, I'm fixing it in this pull request.

**Comment by PierreRambaud** [comment]
Need to merge #276 first, then the PHPStan configuration will be fixed :)

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — COMMENTED** [review]
Code is good but I think it would be not too hard to preserve backward compatibility. Is there a reason for the BC break ?

**Comment by PierreRambaud** [comment]
> Code is good but I think it would be not too hard to preserve backward compatibility. Is there a reason for the BC break ?

Because it's totally broken :sweat:

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
> > Code is good but I think it would be not too hard to preserve backward compatibility. Is there a reason for the BC break ?
> 
> Because it's totally broken 😓

Everything in PrestaShop is broken :trollface: so we can make BC everywhere?

(just a joke, I 👍  the PR)

**Review by matks — APPROVED** [review]

**Pull request merged**
