### PR TITLE
Migrated attribute page compatibility

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This PR integrates the module into the migrated page for AttributeGroup and Attribute
| Type?         | new feature
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Partially fixes #10508
| How to test?  | Test that the module integrates its custom fields properly into the net migrate AttributeGroup and Attribute pages It should still work appropriately on legacy pages (so to be tested on 1.7.8 or 8)

### CODE REVIEW

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
@PrestaShop/qa-functional @jolelievre 

Guys, please test one scenario:
- I am on 1.7.8
- I upgrade this module to 3.15.0 or install it fresh.
- I upgrade to 9.0.0
- Do the hooks work or they need to be rehooked?

**Comment by jolelievre** [comment]
> @jolelievre I resolved this with adding an `ON DUPLICATE KEY UPDATE` statements to insertions. 👍 [PrestaShop/autoupgrade#669](https://github.com/PrestaShop/autoupgrade/pull/669)

Wow! Nice and efficient, I love it!

**Review by florine2623 — APPROVED** [review]
Hello @jolelievre ,

Tested the module faceted search.

Bump to 3.1.5.0 successful ✅ 

Addition of new hooks successful ✅ 

CRUD new products with new attributes/new attributes values
Configure filter template
Check in FO if filter with faceted search works 

I have found a regression. It shouldn't be blocking this PR. It can be fixed in another PR. Here's the issue : https://github.com/PrestaShop/PrestaShop/issues/35331
This issue is 'fixed' after I did an upgrade of PS.

Here are the steps to reproduce :
Create an attribute group + some attribute values
Create a combination product with these attributes
Go to faceted_search module > Enable attribute group > Build attributes and features indexed
Go to FO > Filter the attributes
Go to BO > Delete one attribute > Configure faceted_search > Rebuild the index
Go to FO > See that the attribute is still displayed and the page loads with no filter :x:

https://github.com/PrestaShop/ps_facetedsearch/assets/16019289/4352fc4a-b772-45c9-9436-6db4a14fbde2

Upgrade to 8.1.x ✅ 

It is QA ✅

**Comment by jolelievre** [comment]
Thanks @florine2623

**Pull request merged**
