### PR TITLE
v3.13.0

### PR DESCRIPTION
**Pull request by lartist**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | PR for the release v3.13.0
| Type?         | new feature
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | 
| How to test?  | 

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/887)

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Please wait a bit, sortable path still not QAd - https://github.com/PrestaShop/ps_facetedsearch/pull/881

**Comment by lartist** [comment]
> Please wait a bit, sortable path still not QAd - #881

I'm blocked for this PR https://github.com/PrestaShop/PrestaShop/pull/33051

Maybe we can make another release for your PR

**Review by Hlavtox — APPROVED** [review]

**Comment by djoelleuch** [comment]
hello @lartist  , Some checks were not successful
could you please check  .
thanks

**Comment by lartist** [comment]
Done @djoelleuch

**Review by djoelleuch — APPROVED** [review]
Hello @lartist  ,
Tested on PS 1.7.8.9 , PS 8.0.4 .
LGTM ,it's QA :heavy_check_mark:

Thank you !

**Comment by Hlavtox** [comment]
Thanks @lartist & @djoelleuch, let's go! :-)

**Pull request merged**
