### PR TITLE
Replace ' ' with '\s' in filter label regex

### PR DESCRIPTION
**Pull request by neonVoice**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Change `' '` to `'\s'` in filter label regex, so that regex matching function properly returns groups for replacement.<br/>Before: `/([^\d]*)(?:[\d .,]+)([^\d]+)(?:[\d .,]+)(.*)/`<br/>After: `/([^\d]*)(?:[\d\s.,]+)([^\d]+)(?:[\d\s.,]+)(.*)/`.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#22135.
| How to test?  | 1. Set weight property for 1-2 products<br/>2. Enable weight range filter in Facetedsearch module for main catalogue page<br/>3. Go to main catalogue page and try to use filter.<br/>4. Filter label should display proper value ranges:<br/>Good: `(min)(unit) - (max)(unit)` for example `123g - 12345g`.<br/>Bad: `(min)(unit) - (max)(part of max)(unit)` for example `123g - 12345 345g`.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/ps_facetedsearch/269)

### CODE REVIEW

**Comment by neonVoice** [comment]
I'm not sure about a lot of changes in `\views\dist` folder, currently using windows environment.

**Comment by neonVoice** [comment]
modified webpack config, because resulting JS produced error: `Uncaught TypeError: WEBPACK_IMPORTED_MODULE_1__.default`
https://stackoverflow.com/questions/64316510/uncaught-typeerror-webpack-imported-module-1-default-is-undefined-react-sas

**Comment by atomiix** [comment]
Hi @neonVoice, thanks for your contribution but there is a lot of modified files that are not related to the change you propose. Can you please clean them?

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
PR rebased :)

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
