### PR TITLE
 Add form modifications for feature-value migrated form

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Adds fields url and meta_title fields to migrated feature value form in BO.
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | related to almost finished migration of Features BO form - https://github.com/PrestaShop/PrestaShop/pull/33015
| How to test?  | Use the following PR branch https://github.com/PrestaShop/PrestaShop/pull/33051 - and check that feature value form has additional url and meta_title fields added. Then we will be able to update module version and release it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/PrestaShop/ps_facetedsearch/859)

### CODE REVIEW

**Comment by zuk3975** [comment]
what version should I make it?
`3.12.1 -> 3.12.2` ?

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Review by boherm — APPROVED** [review]

**Comment by zuk3975** [comment]
> what version should I make it? `3.12.1 -> 3.12.2` ?

@jolelievre 
I see approvals already, but shouldn't I update the module version? I wasn't 100% about that one :arrow_up:

**Review by jolelievre — APPROVED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
Missing upgrade file modification.

**Review by kpodemski — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by djoelleuch** [comment]
Hello @zuk3975  
some checks where not successful could you please check .
thank you  .

**Comment by zuk3975** [comment]
I only now saw that I've created additional branch instead of making PR from my fork. Idk if that was causing the build to fail, So I've created a new one the right way now. https://github.com/PrestaShop/ps_facetedsearch/pull/862

**Pull request closed without merging**
